// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNy2IT0DZW95ayIvdz6yXM7yEJjeJ3nBo',
    appId: '1:1050272966389:web:cad403e1339e048191c7bc',
    messagingSenderId: '1050272966389',
    projectId: 'makikain',
    authDomain: 'makikain.firebaseapp.com',
    storageBucket: 'makikain.firebasestorage.app',
    measurementId: 'G-HY70FDSKD8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT95C-GWA-E1ySoYQpJJHTNOtLc1B1KX8',
    appId: '1:1050272966389:android:b2ecee39000de2fa91c7bc',
    messagingSenderId: '1050272966389',
    projectId: 'makikain',
    storageBucket: 'makikain.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAguvaeT_98gH7CmD8pPA9omTdA6ZjYRgE',
    appId: '1:1050272966389:ios:4abc00198f30931291c7bc',
    messagingSenderId: '1050272966389',
    projectId: 'makikain',
    storageBucket: 'makikain.firebasestorage.app',
    iosBundleId: 'com.example.makikain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAguvaeT_98gH7CmD8pPA9omTdA6ZjYRgE',
    appId: '1:1050272966389:ios:4abc00198f30931291c7bc',
    messagingSenderId: '1050272966389',
    projectId: 'makikain',
    storageBucket: 'makikain.firebasestorage.app',
    iosBundleId: 'com.example.makikain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNy2IT0DZW95ayIvdz6yXM7yEJjeJ3nBo',
    appId: '1:1050272966389:web:6e9c09de4b8fcaba91c7bc',
    messagingSenderId: '1050272966389',
    projectId: 'makikain',
    authDomain: 'makikain.firebaseapp.com',
    storageBucket: 'makikain.firebasestorage.app',
    measurementId: 'G-48TRX4SGSZ',
  );
}
